apiVersion: v1  
kind: ConfigMap  
metadata:
  name: catalog-config   
  labels:     
    app: catalog-service
data:   
  application.yml: |     
    line:
      greeting: Welcome to the book catalog from Kubernetes!
    spring:
      datasource:
        url: jdbc:postgresql://line-postgres/linedb_catalog
      security:
        oauth2:
          resourceserver:
            jwt:
              issuer-uri: http://line-keycloak/realms/LineBookstore
